name: Issue Autoresponse

on:
  issues:
    types: [opened]

jobs:
  mirror:
    runs-on: [ubuntu-latest]
    steps:
    - uses: athorp96/sourcehut_issue_mirror@master
      with:
        title: ${{ github.event.issue.title }}
        body: ${{ github.event.issue.body }}
        submitter: ${{ github.event.issue.user.login }}
        tracker-owner: "~athorp96"
        tracker-name: "sourcehut-issue-mirror-github-action"
        oauth-token: ${{ secrets.SRHT_OAUTH_TOKEN }}
        label: ${{ github.event.repository.name }}

  label_mirrored:
    runs-on: [ubuntu-latest]
    steps:
    - uses: Naturalclar/issue-action@v1.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        keywords: '["${{ github.event.issue.body }}"]' # Try and use body as keyword
        labels: '["mirrored","ready-to-close"]'
        
  auto-response:
    runs-on: ubuntu-latest
    steps:
    - uses: derekprior/add-autoresponse@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        respondableId: ${{ github.event.issue.node_id }}
        response: "Hello! Thank you for your interest in my project.\nObviously the project has to be hosted on Github, but our issue tracking is done using sourcehut.\nThis issue has been mirrored on sourcehut using this very github action (big surprise there, right?). Feel free to check it out [here!](https://todo.sr.ht/~athorp96/sourcehut-issue-mirror-github-action)\nThanks!"
        author: ${{ github.event.issue.user.login }}

        
  close-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: issue-closure
      uses: bdougie/close-issues-based-on-label@master
      env:
        LABEL: ready-to-close
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
